<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 10px; color: #1e293b; margin: 0; padding: 20px; }
        h1 { font-size: 16px; font-weight: 700; margin: 0 0 4px; }
        .sub { font-size: 10px; color: #64748b; margin-bottom: 16px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
        th { background: #f8fafc; font-size: 8px; font-weight: 700; text-transform: uppercase;
             letter-spacing: .04em; color: #64748b; padding: 6px 8px; border-bottom: 2px solid #e2e8f0; text-align: left; }
        td { padding: 6px 8px; border-bottom: 1px solid #f1f5f9; font-size: 9px; vertical-align: top; }
        .badge { padding: 2px 6px; border-radius: 4px; font-size: 8px; font-weight: 600; }
        .b-pending  { background:#fffbeb; color:#d97706; }
        .b-approved { background:#eff6ff; color:#1d4ed8; }
        .b-disbursed{ background:#f0fdf4; color:#16a34a; }
        .b-rejected { background:#fef2f2; color:#dc2626; }
        .stats-row { display: table; width: 100%; margin-bottom: 16px; }
        .footer { font-size: 9px; color: #94a3b8; margin-top: 16px; border-top: 1px solid #e2e8f0; padding-top: 8px; }
    </style>
</head>
<body>

<h1>ACLC Clinic — Visit Logs Report</h1>
<div class="sub">{{ now()->format('F j, Y \a\t g:i A') }} — ACLC College of Mandaue</div>

{{-- Active Filters Summary --}}
@php
    $filters = [];
    if(request('search'))    $filters[] = 'Search: "' . request('search') . '"';
    if(request('date_from')) $filters[] = 'From: ' . request('date_from');
    if(request('date_to'))   $filters[] = 'To: ' . request('date_to');
    if(request('status'))    $filters[] = 'Status: ' . ucfirst(request('status'));
@endphp
@if(count($filters))
<div style="background:#eff6ff;border:1px solid #bfdbfe;border-radius:6px;padding:8px 12px;margin-bottom:14px;font-size:9px;color:#1d4ed8;">
    <strong>Filtered by:</strong> {{ implode(' &nbsp;|&nbsp; ', $filters) }}
    &nbsp;&mdash;&nbsp; <strong>{{ $visits->count() }}</strong> record(s) shown
</div>
@endif

{{-- Stats --}}
<table style="margin-bottom:16px;width:auto;">
    <tr>
        <td style="padding:8px 14px;border:1px solid #e2e8f0;border-radius:6px;text-align:center;">
            <div style="font-size:18px;font-weight:700;">{{ $totalVisits }}</div>
            <div style="font-size:8px;color:#64748b;">Total Visits</div>
        </td>
        <td style="width:10px;"></td>
        <td style="padding:8px 14px;border:1px solid #e2e8f0;border-radius:6px;text-align:center;">
            <div style="font-size:18px;font-weight:700;color:#16a34a;">{{ $todayVisits }}</div>
            <div style="font-size:8px;color:#64748b;">Today</div>
        </td>
        <td style="width:10px;"></td>
        <td style="padding:8px 14px;border:1px solid #e2e8f0;border-radius:6px;text-align:center;">
            <div style="font-size:18px;font-weight:700;color:#1d4ed8;">{{ $thisMonth }}</div>
            <div style="font-size:8px;color:#64748b;">This Month</div>
        </td>
    </tr>
</table>

<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Student</th>
            <th>Course / Year</th>
            <th>Reason</th>
            <th>Medications Given</th>
            <th>Status</th>
            <th>Processed By</th>
            <th>Date</th>
        </tr>
    </thead>
    <tbody>
        @forelse($visits as $visit)
        <tr>
            <td style="color:#94a3b8;">{{ $visit->id }}</td>
            <td style="font-weight:600;">{{ $visit->student_name ?? '—' }}</td>
            <td>{{ $visit->course ?? '—' }}{{ $visit->year_level ? ' / '.$visit->year_level : '' }}</td>
            <td>{{ \Illuminate\Support\Str::limit($visit->reason ?? '—', 40) }}</td>
            <td>
                @foreach($visit->items as $item)
                    {{ $item->medication->name ?? '?' }} ({{ $item->quantity }})@if(!$loop->last), @endif
                @endforeach
            </td>
            <td>
                @php
                    $cls = match($visit->status) {
                        'pending'   => 'b-pending',
                        'approved'  => 'b-approved',
                        'disbursed' => 'b-disbursed',
                        'rejected'  => 'b-rejected',
                        default     => '',
                    };
                @endphp
                <span class="badge {{ $cls }}">{{ ucfirst($visit->status) }}</span>
            </td>
            <td>{{ $visit->approver?->name ?? '—' }}</td>
            <td style="white-space:nowrap;">{{ $visit->created_at->format('M d, Y') }}</td>
        </tr>
        @empty
        <tr><td colspan="8" style="text-align:center;color:#94a3b8;padding:12px;">No records found.</td></tr>
        @endforelse
    </tbody>
</table>

<div class="footer">Generated by ACLC Clinic Information &amp; Inventory System &middot; {{ now()->format('F j, Y \a\t g:i A') }}</div>
</body>
</html>
